load("@pip//:requirements.bzl", "all_requirements")

py_binary(
    name = "ipython",
    srcs = ["ipython.py"],
    main = "ipython.py",
    visibility = ["//visibility:public"],
    deps = all_requirements,
)
