# This file is generated by rules_pycross.
# It is not intended for manual editing.

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@jvolkman_rules_pycross//pycross:defs.bzl", "pycross_wheel_build", "pycross_wheel_library", "pypi_file")

PINS = {
    "anyio": "anyio_4.0.0",
    "appnope": "appnope_0.1.3",
    "argon2_cffi": "argon2_cffi_23.1.0",
    "argon2_cffi_bindings": "argon2_cffi_bindings_21.2.0",
    "arrow": "arrow_1.3.0",
    "asttokens": "asttokens_2.4.1",
    "async_lru": "async_lru_2.0.4",
    "attrs": "attrs_23.1.0",
    "babel": "babel_2.13.1",
    "backcall": "backcall_0.2.0",
    "beautifulsoup4": "beautifulsoup4_4.12.2",
    "black": "black_23.7.0",
    "bleach": "bleach_6.1.0",
    "certifi": "certifi_2023.7.22",
    "cffi": "cffi_1.16.0",
    "cfgv": "cfgv_3.4.0",
    "charset_normalizer": "charset_normalizer_3.3.2",
    "click": "click_8.1.7",
    "comm": "comm_0.2.0",
    "cpplint": "cpplint_1.6.1",
    "debugpy": "debugpy_1.8.0",
    "decorator": "decorator_5.1.1",
    "defusedxml": "defusedxml_0.7.1",
    "distlib": "distlib_0.3.7",
    "exceptiongroup": "exceptiongroup_1.1.3",
    "executing": "executing_2.0.1",
    "fastjsonschema": "fastjsonschema_2.18.1",
    "filelock": "filelock_3.13.1",
    "fqdn": "fqdn_1.5.1",
    "identify": "identify_2.5.31",
    "idna": "idna_3.4",
    "importlib_metadata": "importlib_metadata_6.8.0",
    "ipykernel": "ipykernel_6.26.0",
    "ipython": "ipython_8.0.1",
    "isoduration": "isoduration_20.11.0",
    "jedi": "jedi_0.19.1",
    "jinja2": "jinja2_3.1.2",
    "json5": "json5_0.9.14",
    "jsonpointer": "jsonpointer_2.4",
    "jsonschema": "jsonschema_4.19.2",
    "jsonschema_specifications": "jsonschema_specifications_2023.7.1",
    "jupyter_black": "jupyter_black_0.3.4",
    "jupyter_client": "jupyter_client_8.6.0",
    "jupyter_core": "jupyter_core_5.5.0",
    "jupyter_events": "jupyter_events_0.9.0",
    "jupyter_lsp": "jupyter_lsp_2.2.0",
    "jupyter_server": "jupyter_server_2.10.0",
    "jupyter_server_terminals": "jupyter_server_terminals_0.4.4",
    "jupyterlab": "jupyterlab_4.0.8",
    "jupyterlab_pygments": "jupyterlab_pygments_0.2.2",
    "jupyterlab_server": "jupyterlab_server_2.25.1",
    "markupsafe": "markupsafe_2.1.3",
    "matplotlib_inline": "matplotlib_inline_0.1.6",
    "mistune": "mistune_3.0.2",
    "mypy_extensions": "mypy_extensions_1.0.0",
    "nbclient": "nbclient_0.9.0",
    "nbconvert": "nbconvert_7.11.0",
    "nbformat": "nbformat_5.9.2",
    "nest_asyncio": "nest_asyncio_1.5.8",
    "nodeenv": "nodeenv_1.8.0",
    "notebook": "notebook_7.0.6",
    "notebook_shim": "notebook_shim_0.2.3",
    "numpy": "numpy_1.25.2",
    "overrides": "overrides_7.4.0",
    "packaging": "packaging_23.2",
    "pandocfilters": "pandocfilters_1.5.0",
    "parso": "parso_0.8.3",
    "pathspec": "pathspec_0.11.2",
    "pexpect": "pexpect_4.8.0",
    "pickleshare": "pickleshare_0.7.5",
    "platformdirs": "platformdirs_3.11.0",
    "pre_commit": "pre_commit_3.3.3",
    "prometheus_client": "prometheus_client_0.18.0",
    "prompt_toolkit": "prompt_toolkit_3.0.39",
    "psutil": "psutil_5.9.6",
    "ptyprocess": "ptyprocess_0.7.0",
    "pure_eval": "pure_eval_0.2.2",
    "pycparser": "pycparser_2.21",
    "pygments": "pygments_2.16.1",
    "python_dateutil": "python_dateutil_2.8.2",
    "python_json_logger": "python_json_logger_2.0.7",
    "pyyaml": "pyyaml_6.0.1",
    "pyzmq": "pyzmq_25.1.1",
    "referencing": "referencing_0.30.2",
    "requests": "requests_2.31.0",
    "rfc3339_validator": "rfc3339_validator_0.1.4",
    "rfc3986_validator": "rfc3986_validator_0.1.1",
    "rpds_py": "rpds_py_0.12.0",
    "send2trash": "send2trash_1.8.2",
    "setuptools": "setuptools_68.2.2",
    "six": "six_1.16.0",
    "sniffio": "sniffio_1.3.0",
    "soupsieve": "soupsieve_2.5",
    "stack_data": "stack_data_0.6.3",
    "terminado": "terminado_0.17.1",
    "tinycss2": "tinycss2_1.2.1",
    "tokenize_rt": "tokenize_rt_5.2.0",
    "tomli": "tomli_2.0.1",
    "tornado": "tornado_6.3.3",
    "traitlets": "traitlets_5.13.0",
    "types_python_dateutil": "types_python_dateutil_2.8.19.14",
    "typing_extensions": "typing_extensions_4.8.0",
    "uri_template": "uri_template_1.3.0",
    "urllib3": "urllib3_2.0.7",
    "virtualenv": "virtualenv_20.24.6",
    "wcwidth": "wcwidth_0.2.9",
    "webcolors": "webcolors_1.13",
    "webencodings": "webencodings_0.5.1",
    "websocket_client": "websocket_client_1.6.4",
    "zipp": "zipp_3.17.0",
}

def targets():
    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.config_setting(
        name = "_env_python_darwin_arm64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:aarch64",
        ],
    )

    native.config_setting(
        name = "_env_python_darwin_x86_64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:x86_64",
        ],
    )

    native.config_setting(
        name = "_env_python_linux_x86_64",
        constraint_values = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    )

    _target = select({
        ":_env_python_darwin_arm64": "@//toolchain/python/poetry:python_darwin_arm64",
        ":_env_python_darwin_x86_64": "@//toolchain/python/poetry:python_darwin_x86_64",
        ":_env_python_linux_x86_64": "@//toolchain/python/poetry:python_linux_x86_64",
    })

    _anyio_4_0_0_deps = [
        ":exceptiongroup_1.1.3",
        ":idna_3.4",
        ":sniffio_1.3.0",
    ]

    pycross_wheel_library(
        name = "anyio_4.0.0",
        deps = _anyio_4_0_0_deps,
        wheel = "@poetry_lock_wheel_anyio_4.0.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "appnope_0.1.3",
        wheel = "@poetry_lock_wheel_appnope_0.1.3_py2.py3_none_any//file",
    )

    _argon2_cffi_23_1_0_deps = [
        ":argon2_cffi_bindings_21.2.0",
    ]

    pycross_wheel_library(
        name = "argon2_cffi_23.1.0",
        deps = _argon2_cffi_23_1_0_deps,
        wheel = "@poetry_lock_wheel_argon2_cffi_23.1.0_py3_none_any//file",
    )

    _argon2_cffi_bindings_21_2_0_deps = [
        ":cffi_1.16.0",
    ]

    pycross_wheel_library(
        name = "argon2_cffi_bindings_21.2.0",
        deps = _argon2_cffi_bindings_21_2_0_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_argon2_cffi_bindings_21.2.0_cp38_abi3_macosx_10_9_universal2//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_argon2_cffi_bindings_21.2.0_cp38_abi3_macosx_10_9_universal2//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_argon2_cffi_bindings_21.2.0_cp36_abi3_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _arrow_1_3_0_deps = [
        ":python_dateutil_2.8.2",
        ":types_python_dateutil_2.8.19.14",
    ]

    pycross_wheel_library(
        name = "arrow_1.3.0",
        deps = _arrow_1_3_0_deps,
        wheel = "@poetry_lock_wheel_arrow_1.3.0_py3_none_any//file",
    )

    _asttokens_2_4_1_deps = [
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "asttokens_2.4.1",
        deps = _asttokens_2_4_1_deps,
        wheel = "@poetry_lock_wheel_asttokens_2.4.1_py2.py3_none_any//file",
    )

    _async_lru_2_0_4_deps = [
        ":typing_extensions_4.8.0",
    ]

    pycross_wheel_library(
        name = "async_lru_2.0.4",
        deps = _async_lru_2_0_4_deps,
        wheel = "@poetry_lock_wheel_async_lru_2.0.4_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "attrs_23.1.0",
        wheel = "@poetry_lock_wheel_attrs_23.1.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "babel_2.13.1",
        wheel = "@poetry_lock_wheel_babel_2.13.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "backcall_0.2.0",
        wheel = "@poetry_lock_wheel_backcall_0.2.0_py2.py3_none_any//file",
    )

    _beautifulsoup4_4_12_2_deps = [
        ":soupsieve_2.5",
    ]

    pycross_wheel_library(
        name = "beautifulsoup4_4.12.2",
        deps = _beautifulsoup4_4_12_2_deps,
        wheel = "@poetry_lock_wheel_beautifulsoup4_4.12.2_py3_none_any//file",
    )

    _black_23_7_0_deps = [
        ":click_8.1.7",
        ":mypy_extensions_1.0.0",
        ":packaging_23.2",
        ":pathspec_0.11.2",
        ":platformdirs_3.11.0",
        ":tomli_2.0.1",
        ":typing_extensions_4.8.0",
    ]

    pycross_wheel_library(
        name = "black_23.7.0",
        deps = _black_23_7_0_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_black_23.7.0_cp39_cp39_macosx_10_16_universal2//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_black_23.7.0_cp39_cp39_macosx_10_16_x86_64//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_black_23.7.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _bleach_6_1_0_deps = [
        ":six_1.16.0",
        ":webencodings_0.5.1",
    ]

    pycross_wheel_library(
        name = "bleach_6.1.0",
        deps = _bleach_6_1_0_deps,
        wheel = "@poetry_lock_wheel_bleach_6.1.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "certifi_2023.7.22",
        wheel = "@poetry_lock_wheel_certifi_2023.7.22_py3_none_any//file",
    )

    _cffi_1_16_0_deps = [
        ":pycparser_2.21",
    ]

    pycross_wheel_library(
        name = "cffi_1.16.0",
        deps = _cffi_1_16_0_deps,
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_cffi_1.16.0_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_cffi_1.16.0_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_cffi_1.16.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "cfgv_3.4.0",
        wheel = "@poetry_lock_wheel_cfgv_3.4.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "charset_normalizer_3.3.2",
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "click_8.1.7",
        wheel = "@poetry_lock_wheel_click_8.1.7_py3_none_any//file",
    )

    _comm_0_2_0_deps = [
        ":traitlets_5.13.0",
    ]

    pycross_wheel_library(
        name = "comm_0.2.0",
        deps = _comm_0_2_0_deps,
        wheel = "@poetry_lock_wheel_comm_0.2.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "cpplint_1.6.1",
        wheel = "@poetry_lock_wheel_cpplint_1.6.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "debugpy_1.8.0",
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_debugpy_1.8.0_py2.py3_none_any//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_debugpy_1.8.0_cp39_cp39_macosx_11_0_x86_64//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_debugpy_1.8.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "decorator_5.1.1",
        wheel = "@poetry_lock_wheel_decorator_5.1.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "defusedxml_0.7.1",
        wheel = "@poetry_lock_wheel_defusedxml_0.7.1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "distlib_0.3.7",
        wheel = "@poetry_lock_wheel_distlib_0.3.7_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "exceptiongroup_1.1.3",
        wheel = "@poetry_lock_wheel_exceptiongroup_1.1.3_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "executing_2.0.1",
        wheel = "@poetry_lock_wheel_executing_2.0.1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "fastjsonschema_2.18.1",
        wheel = "@poetry_lock_wheel_fastjsonschema_2.18.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "filelock_3.13.1",
        wheel = "@poetry_lock_wheel_filelock_3.13.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "fqdn_1.5.1",
        wheel = "@poetry_lock_wheel_fqdn_1.5.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "identify_2.5.31",
        wheel = "@poetry_lock_wheel_identify_2.5.31_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "idna_3.4",
        wheel = "@poetry_lock_wheel_idna_3.4_py3_none_any//file",
    )

    _importlib_metadata_6_8_0_deps = [
        ":zipp_3.17.0",
    ]

    pycross_wheel_library(
        name = "importlib_metadata_6.8.0",
        deps = _importlib_metadata_6_8_0_deps,
        wheel = "@poetry_lock_wheel_importlib_metadata_6.8.0_py3_none_any//file",
    )

    _ipykernel_6_26_0_deps = [
        ":comm_0.2.0",
        ":debugpy_1.8.0",
        ":ipython_8.0.1",
        ":jupyter_client_8.6.0",
        ":jupyter_core_5.5.0",
        ":matplotlib_inline_0.1.6",
        ":nest_asyncio_1.5.8",
        ":packaging_23.2",
        ":psutil_5.9.6",
        ":pyzmq_25.1.1",
        ":tornado_6.3.3",
        ":traitlets_5.13.0",
    ] + select({
        ":_env_python_darwin_arm64": [
            ":appnope_0.1.3",
        ],
        ":_env_python_darwin_x86_64": [
            ":appnope_0.1.3",
        ],
        "//conditions:default": [],
    })

    pycross_wheel_library(
        name = "ipykernel_6.26.0",
        deps = _ipykernel_6_26_0_deps,
        wheel = "@poetry_lock_wheel_ipykernel_6.26.0_py3_none_any//file",
    )

    _ipython_8_0_1_deps = [
        ":backcall_0.2.0",
        ":black_23.7.0",
        ":decorator_5.1.1",
        ":jedi_0.19.1",
        ":matplotlib_inline_0.1.6",
        ":pexpect_4.8.0",
        ":pickleshare_0.7.5",
        ":prompt_toolkit_3.0.39",
        ":pygments_2.16.1",
        ":setuptools_68.2.2",
        ":stack_data_0.6.3",
        ":traitlets_5.13.0",
    ] + select({
        ":_env_python_darwin_arm64": [
            ":appnope_0.1.3",
        ],
        ":_env_python_darwin_x86_64": [
            ":appnope_0.1.3",
        ],
        "//conditions:default": [],
    })

    pycross_wheel_library(
        name = "ipython_8.0.1",
        deps = _ipython_8_0_1_deps,
        wheel = "@poetry_lock_wheel_ipython_8.0.1_py3_none_any//file",
    )

    _isoduration_20_11_0_deps = [
        ":arrow_1.3.0",
    ]

    pycross_wheel_library(
        name = "isoduration_20.11.0",
        deps = _isoduration_20_11_0_deps,
        wheel = "@poetry_lock_wheel_isoduration_20.11.0_py3_none_any//file",
    )

    _jedi_0_19_1_deps = [
        ":parso_0.8.3",
    ]

    pycross_wheel_library(
        name = "jedi_0.19.1",
        deps = _jedi_0_19_1_deps,
        wheel = "@poetry_lock_wheel_jedi_0.19.1_py2.py3_none_any//file",
    )

    _jinja2_3_1_2_deps = [
        ":markupsafe_2.1.3",
    ]

    pycross_wheel_library(
        name = "jinja2_3.1.2",
        deps = _jinja2_3_1_2_deps,
        wheel = "@poetry_lock_wheel_jinja2_3.1.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "json5_0.9.14",
        wheel = "@poetry_lock_wheel_json5_0.9.14_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "jsonpointer_2.4",
        wheel = "@poetry_lock_wheel_jsonpointer_2.4_py2.py3_none_any//file",
    )

    _jsonschema_4_19_2_deps = [
        ":attrs_23.1.0",
        ":fqdn_1.5.1",
        ":idna_3.4",
        ":isoduration_20.11.0",
        ":jsonpointer_2.4",
        ":jsonschema_specifications_2023.7.1",
        ":referencing_0.30.2",
        ":rfc3339_validator_0.1.4",
        ":rfc3986_validator_0.1.1",
        ":rpds_py_0.12.0",
        ":uri_template_1.3.0",
        ":webcolors_1.13",
    ]

    pycross_wheel_library(
        name = "jsonschema_4.19.2",
        deps = _jsonschema_4_19_2_deps,
        wheel = "@poetry_lock_wheel_jsonschema_4.19.2_py3_none_any//file",
    )

    _jsonschema_specifications_2023_7_1_deps = [
        ":referencing_0.30.2",
    ]

    pycross_wheel_library(
        name = "jsonschema_specifications_2023.7.1",
        deps = _jsonschema_specifications_2023_7_1_deps,
        wheel = "@poetry_lock_wheel_jsonschema_specifications_2023.7.1_py3_none_any//file",
    )

    _jupyter_black_0_3_4_deps = [
        ":black_23.7.0",
        ":ipython_8.0.1",
        ":tokenize_rt_5.2.0",
    ]

    pycross_wheel_library(
        name = "jupyter_black_0.3.4",
        deps = _jupyter_black_0_3_4_deps,
        wheel = "@poetry_lock_wheel_jupyter_black_0.3.4_py3_none_any//file",
    )

    _jupyter_client_8_6_0_deps = [
        ":importlib_metadata_6.8.0",
        ":jupyter_core_5.5.0",
        ":python_dateutil_2.8.2",
        ":pyzmq_25.1.1",
        ":tornado_6.3.3",
        ":traitlets_5.13.0",
    ]

    pycross_wheel_library(
        name = "jupyter_client_8.6.0",
        deps = _jupyter_client_8_6_0_deps,
        wheel = "@poetry_lock_wheel_jupyter_client_8.6.0_py3_none_any//file",
    )

    _jupyter_core_5_5_0_deps = [
        ":platformdirs_3.11.0",
        ":traitlets_5.13.0",
    ]

    pycross_wheel_library(
        name = "jupyter_core_5.5.0",
        deps = _jupyter_core_5_5_0_deps,
        wheel = "@poetry_lock_wheel_jupyter_core_5.5.0_py3_none_any//file",
    )

    _jupyter_events_0_9_0_deps = [
        ":jsonschema_4.19.2",
        ":python_json_logger_2.0.7",
        ":pyyaml_6.0.1",
        ":referencing_0.30.2",
        ":rfc3339_validator_0.1.4",
        ":rfc3986_validator_0.1.1",
        ":traitlets_5.13.0",
    ]

    pycross_wheel_library(
        name = "jupyter_events_0.9.0",
        deps = _jupyter_events_0_9_0_deps,
        wheel = "@poetry_lock_wheel_jupyter_events_0.9.0_py3_none_any//file",
    )

    _jupyter_lsp_2_2_0_deps = [
        ":importlib_metadata_6.8.0",
        ":jupyter_server_2.10.0",
    ]

    pycross_wheel_library(
        name = "jupyter_lsp_2.2.0",
        deps = _jupyter_lsp_2_2_0_deps,
        wheel = "@poetry_lock_wheel_jupyter_lsp_2.2.0_py3_none_any//file",
    )

    _jupyter_server_2_10_0_deps = [
        ":anyio_4.0.0",
        ":argon2_cffi_23.1.0",
        ":jinja2_3.1.2",
        ":jupyter_client_8.6.0",
        ":jupyter_core_5.5.0",
        ":jupyter_events_0.9.0",
        ":jupyter_server_terminals_0.4.4",
        ":nbconvert_7.11.0",
        ":nbformat_5.9.2",
        ":overrides_7.4.0",
        ":packaging_23.2",
        ":prometheus_client_0.18.0",
        ":pyzmq_25.1.1",
        ":send2trash_1.8.2",
        ":terminado_0.17.1",
        ":tornado_6.3.3",
        ":traitlets_5.13.0",
        ":websocket_client_1.6.4",
    ]

    pycross_wheel_library(
        name = "jupyter_server_2.10.0",
        deps = _jupyter_server_2_10_0_deps,
        wheel = "@poetry_lock_wheel_jupyter_server_2.10.0_py3_none_any//file",
    )

    _jupyter_server_terminals_0_4_4_deps = [
        ":terminado_0.17.1",
    ]

    pycross_wheel_library(
        name = "jupyter_server_terminals_0.4.4",
        deps = _jupyter_server_terminals_0_4_4_deps,
        wheel = "@poetry_lock_wheel_jupyter_server_terminals_0.4.4_py3_none_any//file",
    )

    _jupyterlab_4_0_8_deps = [
        ":async_lru_2.0.4",
        ":importlib_metadata_6.8.0",
        ":ipykernel_6.26.0",
        ":jinja2_3.1.2",
        ":jupyter_core_5.5.0",
        ":jupyter_lsp_2.2.0",
        ":jupyter_server_2.10.0",
        ":jupyterlab_server_2.25.1",
        ":notebook_shim_0.2.3",
        ":packaging_23.2",
        ":tomli_2.0.1",
        ":tornado_6.3.3",
        ":traitlets_5.13.0",
    ]

    pycross_wheel_library(
        name = "jupyterlab_4.0.8",
        deps = _jupyterlab_4_0_8_deps,
        wheel = "@poetry_lock_wheel_jupyterlab_4.0.8_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "jupyterlab_pygments_0.2.2",
        wheel = "@poetry_lock_wheel_jupyterlab_pygments_0.2.2_py2.py3_none_any//file",
    )

    _jupyterlab_server_2_25_1_deps = [
        ":babel_2.13.1",
        ":importlib_metadata_6.8.0",
        ":jinja2_3.1.2",
        ":json5_0.9.14",
        ":jsonschema_4.19.2",
        ":jupyter_server_2.10.0",
        ":packaging_23.2",
        ":requests_2.31.0",
    ]

    pycross_wheel_library(
        name = "jupyterlab_server_2.25.1",
        deps = _jupyterlab_server_2_25_1_deps,
        wheel = "@poetry_lock_wheel_jupyterlab_server_2.25.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "markupsafe_2.1.3",
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_markupsafe_2.1.3_cp39_cp39_macosx_10_9_universal2//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_markupsafe_2.1.3_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_markupsafe_2.1.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    _matplotlib_inline_0_1_6_deps = [
        ":traitlets_5.13.0",
    ]

    pycross_wheel_library(
        name = "matplotlib_inline_0.1.6",
        deps = _matplotlib_inline_0_1_6_deps,
        wheel = "@poetry_lock_wheel_matplotlib_inline_0.1.6_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "mistune_3.0.2",
        wheel = "@poetry_lock_wheel_mistune_3.0.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "mypy_extensions_1.0.0",
        wheel = "@poetry_lock_wheel_mypy_extensions_1.0.0_py3_none_any//file",
    )

    _nbclient_0_9_0_deps = [
        ":jupyter_client_8.6.0",
        ":jupyter_core_5.5.0",
        ":nbformat_5.9.2",
        ":traitlets_5.13.0",
    ]

    pycross_wheel_library(
        name = "nbclient_0.9.0",
        deps = _nbclient_0_9_0_deps,
        wheel = "@poetry_lock_wheel_nbclient_0.9.0_py3_none_any//file",
    )

    _nbconvert_7_11_0_deps = [
        ":beautifulsoup4_4.12.2",
        ":bleach_6.1.0",
        ":defusedxml_0.7.1",
        ":importlib_metadata_6.8.0",
        ":jinja2_3.1.2",
        ":jupyter_core_5.5.0",
        ":jupyterlab_pygments_0.2.2",
        ":markupsafe_2.1.3",
        ":mistune_3.0.2",
        ":nbclient_0.9.0",
        ":nbformat_5.9.2",
        ":packaging_23.2",
        ":pandocfilters_1.5.0",
        ":pygments_2.16.1",
        ":tinycss2_1.2.1",
        ":traitlets_5.13.0",
    ]

    pycross_wheel_library(
        name = "nbconvert_7.11.0",
        deps = _nbconvert_7_11_0_deps,
        wheel = "@poetry_lock_wheel_nbconvert_7.11.0_py3_none_any//file",
    )

    _nbformat_5_9_2_deps = [
        ":fastjsonschema_2.18.1",
        ":jsonschema_4.19.2",
        ":jupyter_core_5.5.0",
        ":traitlets_5.13.0",
    ]

    pycross_wheel_library(
        name = "nbformat_5.9.2",
        deps = _nbformat_5_9_2_deps,
        wheel = "@poetry_lock_wheel_nbformat_5.9.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "nest_asyncio_1.5.8",
        wheel = "@poetry_lock_wheel_nest_asyncio_1.5.8_py3_none_any//file",
    )

    _nodeenv_1_8_0_deps = [
        ":setuptools_68.2.2",
    ]

    pycross_wheel_library(
        name = "nodeenv_1.8.0",
        deps = _nodeenv_1_8_0_deps,
        wheel = "@poetry_lock_wheel_nodeenv_1.8.0_py2.py3_none_any//file",
    )

    _notebook_7_0_6_deps = [
        ":jupyter_server_2.10.0",
        ":jupyterlab_4.0.8",
        ":jupyterlab_server_2.25.1",
        ":notebook_shim_0.2.3",
        ":tornado_6.3.3",
    ]

    pycross_wheel_library(
        name = "notebook_7.0.6",
        deps = _notebook_7_0_6_deps,
        wheel = "@poetry_lock_wheel_notebook_7.0.6_py3_none_any//file",
    )

    _notebook_shim_0_2_3_deps = [
        ":jupyter_server_2.10.0",
    ]

    pycross_wheel_library(
        name = "notebook_shim_0.2.3",
        deps = _notebook_shim_0_2_3_deps,
        wheel = "@poetry_lock_wheel_notebook_shim_0.2.3_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "numpy_1.25.2",
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_numpy_1.25.2_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_numpy_1.25.2_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_numpy_1.25.2_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "overrides_7.4.0",
        wheel = "@poetry_lock_wheel_overrides_7.4.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "packaging_23.2",
        wheel = "@poetry_lock_wheel_packaging_23.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pandocfilters_1.5.0",
        wheel = "@poetry_lock_wheel_pandocfilters_1.5.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "parso_0.8.3",
        wheel = "@poetry_lock_wheel_parso_0.8.3_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pathspec_0.11.2",
        wheel = "@poetry_lock_wheel_pathspec_0.11.2_py3_none_any//file",
    )

    _pexpect_4_8_0_deps = [
        ":ptyprocess_0.7.0",
    ]

    pycross_wheel_library(
        name = "pexpect_4.8.0",
        deps = _pexpect_4_8_0_deps,
        wheel = "@poetry_lock_wheel_pexpect_4.8.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pickleshare_0.7.5",
        wheel = "@poetry_lock_wheel_pickleshare_0.7.5_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "platformdirs_3.11.0",
        wheel = "@poetry_lock_wheel_platformdirs_3.11.0_py3_none_any//file",
    )

    _pre_commit_3_3_3_deps = [
        ":cfgv_3.4.0",
        ":identify_2.5.31",
        ":nodeenv_1.8.0",
        ":pyyaml_6.0.1",
        ":virtualenv_20.24.6",
    ]

    pycross_wheel_library(
        name = "pre_commit_3.3.3",
        deps = _pre_commit_3_3_3_deps,
        wheel = "@poetry_lock_wheel_pre_commit_3.3.3_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "prometheus_client_0.18.0",
        wheel = "@poetry_lock_wheel_prometheus_client_0.18.0_py3_none_any//file",
    )

    _prompt_toolkit_3_0_39_deps = [
        ":wcwidth_0.2.9",
    ]

    pycross_wheel_library(
        name = "prompt_toolkit_3.0.39",
        deps = _prompt_toolkit_3_0_39_deps,
        wheel = "@poetry_lock_wheel_prompt_toolkit_3.0.39_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "psutil_5.9.6",
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_psutil_5.9.6_cp38_abi3_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_psutil_5.9.6_cp36_abi3_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_psutil_5.9.6_cp36_abi3_manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "ptyprocess_0.7.0",
        wheel = "@poetry_lock_wheel_ptyprocess_0.7.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pure_eval_0.2.2",
        wheel = "@poetry_lock_wheel_pure_eval_0.2.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pycparser_2.21",
        wheel = "@poetry_lock_wheel_pycparser_2.21_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pygments_2.16.1",
        wheel = "@poetry_lock_wheel_pygments_2.16.1_py3_none_any//file",
    )

    _python_dateutil_2_8_2_deps = [
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "python_dateutil_2.8.2",
        deps = _python_dateutil_2_8_2_deps,
        wheel = "@poetry_lock_wheel_python_dateutil_2.8.2_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "python_json_logger_2.0.7",
        wheel = "@poetry_lock_wheel_python_json_logger_2.0.7_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "pyyaml_6.0.1",
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_pyyaml_6.0.1_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_pyyaml_6.0.1_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_pyyaml_6.0.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "pyzmq_25.1.1",
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_pyzmq_25.1.1_cp39_cp39_macosx_10_15_universal2//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_pyzmq_25.1.1_cp39_cp39_macosx_10_15_universal2//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_pyzmq_25.1.1_cp39_cp39_manylinux_2_12_x86_64.manylinux2010_x86_64//file",
        }),
    )

    _referencing_0_30_2_deps = [
        ":attrs_23.1.0",
        ":rpds_py_0.12.0",
    ]

    pycross_wheel_library(
        name = "referencing_0.30.2",
        deps = _referencing_0_30_2_deps,
        wheel = "@poetry_lock_wheel_referencing_0.30.2_py3_none_any//file",
    )

    _requests_2_31_0_deps = [
        ":certifi_2023.7.22",
        ":charset_normalizer_3.3.2",
        ":idna_3.4",
        ":urllib3_2.0.7",
    ]

    pycross_wheel_library(
        name = "requests_2.31.0",
        deps = _requests_2_31_0_deps,
        wheel = "@poetry_lock_wheel_requests_2.31.0_py3_none_any//file",
    )

    _rfc3339_validator_0_1_4_deps = [
        ":six_1.16.0",
    ]

    pycross_wheel_library(
        name = "rfc3339_validator_0.1.4",
        deps = _rfc3339_validator_0_1_4_deps,
        wheel = "@poetry_lock_wheel_rfc3339_validator_0.1.4_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "rfc3986_validator_0.1.1",
        wheel = "@poetry_lock_wheel_rfc3986_validator_0.1.1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "rpds_py_0.12.0",
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_rpds_py_0.12.0_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_rpds_py_0.12.0_cp39_cp39_macosx_10_7_x86_64//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_rpds_py_0.12.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "send2trash_1.8.2",
        wheel = "@poetry_lock_wheel_send2trash_1.8.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "setuptools_68.2.2",
        wheel = "@poetry_lock_wheel_setuptools_68.2.2_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "six_1.16.0",
        wheel = "@poetry_lock_wheel_six_1.16.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "sniffio_1.3.0",
        wheel = "@poetry_lock_wheel_sniffio_1.3.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "soupsieve_2.5",
        wheel = "@poetry_lock_wheel_soupsieve_2.5_py3_none_any//file",
    )

    _stack_data_0_6_3_deps = [
        ":asttokens_2.4.1",
        ":executing_2.0.1",
        ":pure_eval_0.2.2",
    ]

    pycross_wheel_library(
        name = "stack_data_0.6.3",
        deps = _stack_data_0_6_3_deps,
        wheel = "@poetry_lock_wheel_stack_data_0.6.3_py3_none_any//file",
    )

    _terminado_0_17_1_deps = [
        ":ptyprocess_0.7.0",
        ":tornado_6.3.3",
    ]

    pycross_wheel_library(
        name = "terminado_0.17.1",
        deps = _terminado_0_17_1_deps,
        wheel = "@poetry_lock_wheel_terminado_0.17.1_py3_none_any//file",
    )

    _tinycss2_1_2_1_deps = [
        ":webencodings_0.5.1",
    ]

    pycross_wheel_library(
        name = "tinycss2_1.2.1",
        deps = _tinycss2_1_2_1_deps,
        wheel = "@poetry_lock_wheel_tinycss2_1.2.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "tokenize_rt_5.2.0",
        wheel = "@poetry_lock_wheel_tokenize_rt_5.2.0_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "tomli_2.0.1",
        wheel = "@poetry_lock_wheel_tomli_2.0.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "tornado_6.3.3",
        wheel = select({
            ":_env_python_darwin_arm64": "@poetry_lock_wheel_tornado_6.3.3_cp38_abi3_macosx_10_9_universal2//file",
            ":_env_python_darwin_x86_64": "@poetry_lock_wheel_tornado_6.3.3_cp38_abi3_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@poetry_lock_wheel_tornado_6.3.3_cp38_abi3_manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "traitlets_5.13.0",
        wheel = "@poetry_lock_wheel_traitlets_5.13.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "types_python_dateutil_2.8.19.14",
        wheel = "@poetry_lock_wheel_types_python_dateutil_2.8.19.14_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "typing_extensions_4.8.0",
        wheel = "@poetry_lock_wheel_typing_extensions_4.8.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "uri_template_1.3.0",
        wheel = "@poetry_lock_wheel_uri_template_1.3.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "urllib3_2.0.7",
        wheel = "@poetry_lock_wheel_urllib3_2.0.7_py3_none_any//file",
    )

    _virtualenv_20_24_6_deps = [
        ":distlib_0.3.7",
        ":filelock_3.13.1",
        ":platformdirs_3.11.0",
    ]

    pycross_wheel_library(
        name = "virtualenv_20.24.6",
        deps = _virtualenv_20_24_6_deps,
        wheel = "@poetry_lock_wheel_virtualenv_20.24.6_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wcwidth_0.2.9",
        wheel = "@poetry_lock_wheel_wcwidth_0.2.9_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "webcolors_1.13",
        wheel = "@poetry_lock_wheel_webcolors_1.13_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "webencodings_0.5.1",
        wheel = "@poetry_lock_wheel_webencodings_0.5.1_py2.py3_none_any//file",
    )

    pycross_wheel_library(
        name = "websocket_client_1.6.4",
        wheel = "@poetry_lock_wheel_websocket_client_1.6.4_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "zipp_3.17.0",
        wheel = "@poetry_lock_wheel_zipp_3.17.0_py3_none_any//file",
    )

def repositories():
    maybe(
        pypi_file,
        name = "poetry_lock_wheel_anyio_4.0.0_py3_none_any",
        package_name = "anyio",
        package_version = "4.0.0",
        filename = "anyio-4.0.0-py3-none-any.whl",
        sha256 = "cfdb2b588b9fc25ede96d8db56ed50848b0b649dca3dd1df0b11f683bb9e0b5f",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_appnope_0.1.3_py2.py3_none_any",
        package_name = "appnope",
        package_version = "0.1.3",
        filename = "appnope-0.1.3-py2.py3-none-any.whl",
        sha256 = "265a455292d0bd8a72453494fa24df5a11eb18373a60c7c0430889f22548605e",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_argon2_cffi_23.1.0_py3_none_any",
        package_name = "argon2-cffi",
        package_version = "23.1.0",
        filename = "argon2_cffi-23.1.0-py3-none-any.whl",
        sha256 = "c670642b78ba29641818ab2e68bd4e6a78ba53b7eff7b4c3815ae16abf91c7ea",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_argon2_cffi_bindings_21.2.0_cp36_abi3_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "argon2-cffi-bindings",
        package_version = "21.2.0",
        filename = "argon2_cffi_bindings-21.2.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "b746dba803a79238e925d9046a63aa26bf86ab2a2fe74ce6b009a1c3f5c8f2ae",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_argon2_cffi_bindings_21.2.0_cp38_abi3_macosx_10_9_universal2",
        package_name = "argon2-cffi-bindings",
        package_version = "21.2.0",
        filename = "argon2_cffi_bindings-21.2.0-cp38-abi3-macosx_10_9_universal2.whl",
        sha256 = "e415e3f62c8d124ee16018e491a009937f8cf7ebf5eb430ffc5de21b900dad93",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_arrow_1.3.0_py3_none_any",
        package_name = "arrow",
        package_version = "1.3.0",
        filename = "arrow-1.3.0-py3-none-any.whl",
        sha256 = "c728b120ebc00eb84e01882a6f5e7927a53960aa990ce7dd2b10f39005a67f80",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_asttokens_2.4.1_py2.py3_none_any",
        package_name = "asttokens",
        package_version = "2.4.1",
        filename = "asttokens-2.4.1-py2.py3-none-any.whl",
        sha256 = "051ed49c3dcae8913ea7cd08e46a606dba30b79993209636c4875bc1d637bc24",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_async_lru_2.0.4_py3_none_any",
        package_name = "async-lru",
        package_version = "2.0.4",
        filename = "async_lru-2.0.4-py3-none-any.whl",
        sha256 = "ff02944ce3c288c5be660c42dbcca0742b32c3b279d6dceda655190240b99224",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_attrs_23.1.0_py3_none_any",
        package_name = "attrs",
        package_version = "23.1.0",
        filename = "attrs-23.1.0-py3-none-any.whl",
        sha256 = "1f28b4522cdc2fb4256ac1a020c78acf9cba2c6b461ccd2c126f3aa8e8335d04",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_babel_2.13.1_py3_none_any",
        package_name = "babel",
        package_version = "2.13.1",
        filename = "Babel-2.13.1-py3-none-any.whl",
        sha256 = "7077a4984b02b6727ac10f1f7294484f737443d7e2e66c5e4380e41a3ae0b4ed",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_backcall_0.2.0_py2.py3_none_any",
        package_name = "backcall",
        package_version = "0.2.0",
        filename = "backcall-0.2.0-py2.py3-none-any.whl",
        sha256 = "fbbce6a29f263178a1f7915c1940bde0ec2b2a967566fe1c65c1dfb7422bd255",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_beautifulsoup4_4.12.2_py3_none_any",
        package_name = "beautifulsoup4",
        package_version = "4.12.2",
        filename = "beautifulsoup4-4.12.2-py3-none-any.whl",
        sha256 = "bd2520ca0d9d7d12694a53d44ac482d181b4ec1888909b035a3dbf40d0f57d4a",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_black_23.7.0_cp39_cp39_macosx_10_16_universal2",
        package_name = "black",
        package_version = "23.7.0",
        filename = "black-23.7.0-cp39-cp39-macosx_10_16_universal2.whl",
        sha256 = "47e56d83aad53ca140da0af87678fb38e44fd6bc0af71eebab2d1f59b1acf1d3",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_black_23.7.0_cp39_cp39_macosx_10_16_x86_64",
        package_name = "black",
        package_version = "23.7.0",
        filename = "black-23.7.0-cp39-cp39-macosx_10_16_x86_64.whl",
        sha256 = "25cc308838fe71f7065df53aedd20327969d05671bac95b38fdf37ebe70ac087",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_black_23.7.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "black",
        package_version = "23.7.0",
        filename = "black-23.7.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "642496b675095d423f9b8448243336f8ec71c9d4d57ec17bf795b67f08132a91",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_bleach_6.1.0_py3_none_any",
        package_name = "bleach",
        package_version = "6.1.0",
        filename = "bleach-6.1.0-py3-none-any.whl",
        sha256 = "3225f354cfc436b9789c66c4ee030194bee0568fbf9cbdad3bc8b5c26c5f12b6",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_certifi_2023.7.22_py3_none_any",
        package_name = "certifi",
        package_version = "2023.7.22",
        filename = "certifi-2023.7.22-py3-none-any.whl",
        sha256 = "92d6037539857d8206b8f6ae472e8b77db8058fec5937a1ef3f54304089edbb9",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_cffi_1.16.0_cp39_cp39_macosx_10_9_x86_64",
        package_name = "cffi",
        package_version = "1.16.0",
        filename = "cffi-1.16.0-cp39-cp39-macosx_10_9_x86_64.whl",
        sha256 = "582215a0e9adbe0e379761260553ba11c58943e4bbe9c36430c4ca6ac74b15ed",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_cffi_1.16.0_cp39_cp39_macosx_11_0_arm64",
        package_name = "cffi",
        package_version = "1.16.0",
        filename = "cffi-1.16.0-cp39-cp39-macosx_11_0_arm64.whl",
        sha256 = "b29ebffcf550f9da55bec9e02ad430c992a87e5f512cd63388abb76f1036d8d2",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_cffi_1.16.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "cffi",
        package_version = "1.16.0",
        filename = "cffi-1.16.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "8f8e709127c6c77446a8c0a8c8bf3c8ee706a06cd44b1e827c3e6a2ee6b8c098",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_cfgv_3.4.0_py2.py3_none_any",
        package_name = "cfgv",
        package_version = "3.4.0",
        filename = "cfgv-3.4.0-py2.py3-none-any.whl",
        sha256 = "b7265b1f29fd3316bfcd2b330d63d024f2bfd8bcb8b0272f8e19a504856c48f9",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_macosx_10_9_x86_64",
        package_name = "charset-normalizer",
        package_version = "3.3.2",
        filename = "charset_normalizer-3.3.2-cp39-cp39-macosx_10_9_x86_64.whl",
        sha256 = "5b4c145409bef602a690e7cfad0a15a55c13320ff7a3ad7ca59c13bb8ba4d45d",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_macosx_11_0_arm64",
        package_name = "charset-normalizer",
        package_version = "3.3.2",
        filename = "charset_normalizer-3.3.2-cp39-cp39-macosx_11_0_arm64.whl",
        sha256 = "68d1f8a9e9e37c1223b656399be5d6b448dea850bed7d0f87a8311f1ff3dabb0",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_charset_normalizer_3.3.2_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "charset-normalizer",
        package_version = "3.3.2",
        filename = "charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "b261ccdec7821281dade748d088bb6e9b69e6d15b30652b74cbbac25e280b796",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_click_8.1.7_py3_none_any",
        package_name = "click",
        package_version = "8.1.7",
        filename = "click-8.1.7-py3-none-any.whl",
        sha256 = "ae74fb96c20a0277a1d615f1e4d73c8414f5a98db8b799a7931d1582f3390c28",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_comm_0.2.0_py3_none_any",
        package_name = "comm",
        package_version = "0.2.0",
        filename = "comm-0.2.0-py3-none-any.whl",
        sha256 = "2da8d9ebb8dd7bfc247adaff99f24dce705638a8042b85cb995066793e391001",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_cpplint_1.6.1_py3_none_any",
        package_name = "cpplint",
        package_version = "1.6.1",
        filename = "cpplint-1.6.1-py3-none-any.whl",
        sha256 = "00ddc86d6e4de2a9dcfa272402dcbe21593363a93b7c475bc391e335062f34b1",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_debugpy_1.8.0_cp39_cp39_macosx_11_0_x86_64",
        package_name = "debugpy",
        package_version = "1.8.0",
        filename = "debugpy-1.8.0-cp39-cp39-macosx_11_0_x86_64.whl",
        sha256 = "61eab4a4c8b6125d41a34bad4e5fe3d2cc145caecd63c3fe953be4cc53e65bf8",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_debugpy_1.8.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "debugpy",
        package_version = "1.8.0",
        filename = "debugpy-1.8.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "125b9a637e013f9faac0a3d6a82bd17c8b5d2c875fb6b7e2772c5aba6d082332",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_debugpy_1.8.0_py2.py3_none_any",
        package_name = "debugpy",
        package_version = "1.8.0",
        filename = "debugpy-1.8.0-py2.py3-none-any.whl",
        sha256 = "9c9b0ac1ce2a42888199df1a1906e45e6f3c9555497643a85e0bf2406e3ffbc4",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_decorator_5.1.1_py3_none_any",
        package_name = "decorator",
        package_version = "5.1.1",
        filename = "decorator-5.1.1-py3-none-any.whl",
        sha256 = "b8c3f85900b9dc423225913c5aace94729fe1fa9763b38939a95226f02d37186",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_defusedxml_0.7.1_py2.py3_none_any",
        package_name = "defusedxml",
        package_version = "0.7.1",
        filename = "defusedxml-0.7.1-py2.py3-none-any.whl",
        sha256 = "a352e7e428770286cc899e2542b6cdaedb2b4953ff269a210103ec58f6198a61",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_distlib_0.3.7_py2.py3_none_any",
        package_name = "distlib",
        package_version = "0.3.7",
        filename = "distlib-0.3.7-py2.py3-none-any.whl",
        sha256 = "2e24928bc811348f0feb63014e97aaae3037f2cf48712d51ae61df7fd6075057",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_exceptiongroup_1.1.3_py3_none_any",
        package_name = "exceptiongroup",
        package_version = "1.1.3",
        filename = "exceptiongroup-1.1.3-py3-none-any.whl",
        sha256 = "343280667a4585d195ca1cf9cef84a4e178c4b6cf2274caef9859782b567d5e3",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_executing_2.0.1_py2.py3_none_any",
        package_name = "executing",
        package_version = "2.0.1",
        filename = "executing-2.0.1-py2.py3-none-any.whl",
        sha256 = "eac49ca94516ccc753f9fb5ce82603156e590b27525a8bc32cce8ae302eb61bc",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_fastjsonschema_2.18.1_py3_none_any",
        package_name = "fastjsonschema",
        package_version = "2.18.1",
        filename = "fastjsonschema-2.18.1-py3-none-any.whl",
        sha256 = "aec6a19e9f66e9810ab371cc913ad5f4e9e479b63a7072a2cd060a9369e329a8",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_filelock_3.13.1_py3_none_any",
        package_name = "filelock",
        package_version = "3.13.1",
        filename = "filelock-3.13.1-py3-none-any.whl",
        sha256 = "57dbda9b35157b05fb3e58ee91448612eb674172fab98ee235ccb0b5bee19a1c",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_fqdn_1.5.1_py3_none_any",
        package_name = "fqdn",
        package_version = "1.5.1",
        filename = "fqdn-1.5.1-py3-none-any.whl",
        sha256 = "3a179af3761e4df6eb2e026ff9e1a3033d3587bf980a0b1b2e1e5d08d7358014",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_identify_2.5.31_py2.py3_none_any",
        package_name = "identify",
        package_version = "2.5.31",
        filename = "identify-2.5.31-py2.py3-none-any.whl",
        sha256 = "90199cb9e7bd3c5407a9b7e81b4abec4bb9d249991c79439ec8af740afc6293d",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_idna_3.4_py3_none_any",
        package_name = "idna",
        package_version = "3.4",
        filename = "idna-3.4-py3-none-any.whl",
        sha256 = "90b77e79eaa3eba6de819a0c442c0b4ceefc341a7a2ab77d7562bf49f425c5c2",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_importlib_metadata_6.8.0_py3_none_any",
        package_name = "importlib-metadata",
        package_version = "6.8.0",
        filename = "importlib_metadata-6.8.0-py3-none-any.whl",
        sha256 = "3ebb78df84a805d7698245025b975d9d67053cd94c79245ba4b3eb694abe68bb",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_ipykernel_6.26.0_py3_none_any",
        package_name = "ipykernel",
        package_version = "6.26.0",
        filename = "ipykernel-6.26.0-py3-none-any.whl",
        sha256 = "3ba3dc97424b87b31bb46586b5167b3161b32d7820b9201a9e698c71e271602c",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_ipython_8.0.1_py3_none_any",
        package_name = "ipython",
        package_version = "8.0.1",
        filename = "ipython-8.0.1-py3-none-any.whl",
        sha256 = "c503a0dd6ccac9c8c260b211f2dd4479c042b49636b097cc9a0d55fe62dff64c",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_isoduration_20.11.0_py3_none_any",
        package_name = "isoduration",
        package_version = "20.11.0",
        filename = "isoduration-20.11.0-py3-none-any.whl",
        sha256 = "b2904c2a4228c3d44f409c8ae8e2370eb21a26f7ac2ec5446df141dde3452042",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jedi_0.19.1_py2.py3_none_any",
        package_name = "jedi",
        package_version = "0.19.1",
        filename = "jedi-0.19.1-py2.py3-none-any.whl",
        sha256 = "e983c654fe5c02867aef4cdfce5a2fbb4a50adc0af145f70504238f18ef5e7e0",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jinja2_3.1.2_py3_none_any",
        package_name = "jinja2",
        package_version = "3.1.2",
        filename = "Jinja2-3.1.2-py3-none-any.whl",
        sha256 = "6088930bfe239f0e6710546ab9c19c9ef35e29792895fed6e6e31a023a182a61",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_json5_0.9.14_py2.py3_none_any",
        package_name = "json5",
        package_version = "0.9.14",
        filename = "json5-0.9.14-py2.py3-none-any.whl",
        sha256 = "740c7f1b9e584a468dbb2939d8d458db3427f2c93ae2139d05f47e453eae964f",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jsonpointer_2.4_py2.py3_none_any",
        package_name = "jsonpointer",
        package_version = "2.4",
        filename = "jsonpointer-2.4-py2.py3-none-any.whl",
        sha256 = "15d51bba20eea3165644553647711d150376234112651b4f1811022aecad7d7a",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jsonschema_4.19.2_py3_none_any",
        package_name = "jsonschema",
        package_version = "4.19.2",
        filename = "jsonschema-4.19.2-py3-none-any.whl",
        sha256 = "eee9e502c788e89cb166d4d37f43084e3b64ab405c795c03d343a4dbc2c810fc",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jsonschema_specifications_2023.7.1_py3_none_any",
        package_name = "jsonschema-specifications",
        package_version = "2023.7.1",
        filename = "jsonschema_specifications-2023.7.1-py3-none-any.whl",
        sha256 = "05adf340b659828a004220a9613be00fa3f223f2b82002e273dee62fd50524b1",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jupyter_black_0.3.4_py3_none_any",
        package_name = "jupyter-black",
        package_version = "0.3.4",
        filename = "jupyter_black-0.3.4-py3-none-any.whl",
        sha256 = "8690ec1d16d173a74eecc44419755ca7209c494b213e0d7b04c40a878239e247",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jupyter_client_8.6.0_py3_none_any",
        package_name = "jupyter-client",
        package_version = "8.6.0",
        filename = "jupyter_client-8.6.0-py3-none-any.whl",
        sha256 = "909c474dbe62582ae62b758bca86d6518c85234bdee2d908c778db6d72f39d99",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jupyter_core_5.5.0_py3_none_any",
        package_name = "jupyter-core",
        package_version = "5.5.0",
        filename = "jupyter_core-5.5.0-py3-none-any.whl",
        sha256 = "e11e02cd8ae0a9de5c6c44abf5727df9f2581055afe00b22183f621ba3585805",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jupyter_events_0.9.0_py3_none_any",
        package_name = "jupyter-events",
        package_version = "0.9.0",
        filename = "jupyter_events-0.9.0-py3-none-any.whl",
        sha256 = "d853b3c10273ff9bc8bb8b30076d65e2c9685579db736873de6c2232dde148bf",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jupyter_lsp_2.2.0_py3_none_any",
        package_name = "jupyter-lsp",
        package_version = "2.2.0",
        filename = "jupyter_lsp-2.2.0-py3-none-any.whl",
        sha256 = "9e06b8b4f7dd50300b70dd1a78c0c3b0c3d8fa68e0f2d8a5d1fbab62072aca3f",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jupyter_server_2.10.0_py3_none_any",
        package_name = "jupyter-server",
        package_version = "2.10.0",
        filename = "jupyter_server-2.10.0-py3-none-any.whl",
        sha256 = "dde56c9bc3cb52d7b72cc0f696d15d7163603526f1a758eb4a27405b73eab2a5",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jupyter_server_terminals_0.4.4_py3_none_any",
        package_name = "jupyter-server-terminals",
        package_version = "0.4.4",
        filename = "jupyter_server_terminals-0.4.4-py3-none-any.whl",
        sha256 = "75779164661cec02a8758a5311e18bb8eb70c4e86c6b699403100f1585a12a36",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jupyterlab_4.0.8_py3_none_any",
        package_name = "jupyterlab",
        package_version = "4.0.8",
        filename = "jupyterlab-4.0.8-py3-none-any.whl",
        sha256 = "2ff5aa2a51eb21df241d6011c236e88bd1ff9a5dbb75bebc54472f9c18bfffa4",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jupyterlab_pygments_0.2.2_py2.py3_none_any",
        package_name = "jupyterlab-pygments",
        package_version = "0.2.2",
        filename = "jupyterlab_pygments-0.2.2-py2.py3-none-any.whl",
        sha256 = "2405800db07c9f770863bcf8049a529c3dd4d3e28536638bd7c1c01d2748309f",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_jupyterlab_server_2.25.1_py3_none_any",
        package_name = "jupyterlab-server",
        package_version = "2.25.1",
        filename = "jupyterlab_server-2.25.1-py3-none-any.whl",
        sha256 = "dce9714d91fb3e53d2b37d0e0619fa26ed223c8e7b8c81cca112926de19b53a4",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_markupsafe_2.1.3_cp39_cp39_macosx_10_9_universal2",
        package_name = "markupsafe",
        package_version = "2.1.3",
        filename = "MarkupSafe-2.1.3-cp39-cp39-macosx_10_9_universal2.whl",
        sha256 = "8023faf4e01efadfa183e863fefde0046de576c6f14659e8782065bcece22198",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_markupsafe_2.1.3_cp39_cp39_macosx_10_9_x86_64",
        package_name = "markupsafe",
        package_version = "2.1.3",
        filename = "MarkupSafe-2.1.3-cp39-cp39-macosx_10_9_x86_64.whl",
        sha256 = "6b2b56950d93e41f33b4223ead100ea0fe11f8e6ee5f641eb753ce4b77a7042b",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_markupsafe_2.1.3_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "markupsafe",
        package_version = "2.1.3",
        filename = "MarkupSafe-2.1.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "05fb21170423db021895e1ea1e1f3ab3adb85d1c2333cbc2310f2a26bc77272e",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_matplotlib_inline_0.1.6_py3_none_any",
        package_name = "matplotlib-inline",
        package_version = "0.1.6",
        filename = "matplotlib_inline-0.1.6-py3-none-any.whl",
        sha256 = "f1f41aab5328aa5aaea9b16d083b128102f8712542f819fe7e6a420ff581b311",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_mistune_3.0.2_py3_none_any",
        package_name = "mistune",
        package_version = "3.0.2",
        filename = "mistune-3.0.2-py3-none-any.whl",
        sha256 = "71481854c30fdbc938963d3605b72501f5c10a9320ecd412c121c163a1c7d205",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_mypy_extensions_1.0.0_py3_none_any",
        package_name = "mypy-extensions",
        package_version = "1.0.0",
        filename = "mypy_extensions-1.0.0-py3-none-any.whl",
        sha256 = "4392f6c0eb8a5668a69e23d168ffa70f0be9ccfd32b5cc2d26a34ae5b844552d",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_nbclient_0.9.0_py3_none_any",
        package_name = "nbclient",
        package_version = "0.9.0",
        filename = "nbclient-0.9.0-py3-none-any.whl",
        sha256 = "a3a1ddfb34d4a9d17fc744d655962714a866639acd30130e9be84191cd97cd15",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_nbconvert_7.11.0_py3_none_any",
        package_name = "nbconvert",
        package_version = "7.11.0",
        filename = "nbconvert-7.11.0-py3-none-any.whl",
        sha256 = "d1d417b7f34a4e38887f8da5bdfd12372adf3b80f995d57556cb0972c68909fe",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_nbformat_5.9.2_py3_none_any",
        package_name = "nbformat",
        package_version = "5.9.2",
        filename = "nbformat-5.9.2-py3-none-any.whl",
        sha256 = "1c5172d786a41b82bcfd0c23f9e6b6f072e8fb49c39250219e4acfff1efe89e9",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_nest_asyncio_1.5.8_py3_none_any",
        package_name = "nest-asyncio",
        package_version = "1.5.8",
        filename = "nest_asyncio-1.5.8-py3-none-any.whl",
        sha256 = "accda7a339a70599cb08f9dd09a67e0c2ef8d8d6f4c07f96ab203f2ae254e48d",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_nodeenv_1.8.0_py2.py3_none_any",
        package_name = "nodeenv",
        package_version = "1.8.0",
        filename = "nodeenv-1.8.0-py2.py3-none-any.whl",
        sha256 = "df865724bb3c3adc86b3876fa209771517b0cfe596beff01a92700e0e8be4cec",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_notebook_7.0.6_py3_none_any",
        package_name = "notebook",
        package_version = "7.0.6",
        filename = "notebook-7.0.6-py3-none-any.whl",
        sha256 = "0fe8f67102fea3744fedf652e4c15339390902ca70c5a31c4f547fa23da697cc",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_notebook_shim_0.2.3_py3_none_any",
        package_name = "notebook-shim",
        package_version = "0.2.3",
        filename = "notebook_shim-0.2.3-py3-none-any.whl",
        sha256 = "a83496a43341c1674b093bfcebf0fe8e74cbe7eda5fd2bbc56f8e39e1486c0c7",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_numpy_1.25.2_cp39_cp39_macosx_10_9_x86_64",
        package_name = "numpy",
        package_version = "1.25.2",
        filename = "numpy-1.25.2-cp39-cp39-macosx_10_9_x86_64.whl",
        sha256 = "b79e513d7aac42ae918db3ad1341a015488530d0bb2a6abcbdd10a3a829ccfd3",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_numpy_1.25.2_cp39_cp39_macosx_11_0_arm64",
        package_name = "numpy",
        package_version = "1.25.2",
        filename = "numpy-1.25.2-cp39-cp39-macosx_11_0_arm64.whl",
        sha256 = "eb942bfb6f84df5ce05dbf4b46673ffed0d3da59f13635ea9b926af3deb76926",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_numpy_1.25.2_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "numpy",
        package_version = "1.25.2",
        filename = "numpy-1.25.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "d7806500e4f5bdd04095e849265e55de20d8cc4b661b038957354327f6d9b295",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_overrides_7.4.0_py3_none_any",
        package_name = "overrides",
        package_version = "7.4.0",
        filename = "overrides-7.4.0-py3-none-any.whl",
        sha256 = "3ad24583f86d6d7a49049695efe9933e67ba62f0c7625d53c59fa832ce4b8b7d",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_packaging_23.2_py3_none_any",
        package_name = "packaging",
        package_version = "23.2",
        filename = "packaging-23.2-py3-none-any.whl",
        sha256 = "8c491190033a9af7e1d931d0b5dacc2ef47509b34dd0de67ed209b5203fc88c7",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pandocfilters_1.5.0_py2.py3_none_any",
        package_name = "pandocfilters",
        package_version = "1.5.0",
        filename = "pandocfilters-1.5.0-py2.py3-none-any.whl",
        sha256 = "33aae3f25fd1a026079f5d27bdd52496f0e0803b3469282162bafdcbdf6ef14f",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_parso_0.8.3_py2.py3_none_any",
        package_name = "parso",
        package_version = "0.8.3",
        filename = "parso-0.8.3-py2.py3-none-any.whl",
        sha256 = "c001d4636cd3aecdaf33cbb40aebb59b094be2a74c556778ef5576c175e19e75",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pathspec_0.11.2_py3_none_any",
        package_name = "pathspec",
        package_version = "0.11.2",
        filename = "pathspec-0.11.2-py3-none-any.whl",
        sha256 = "1d6ed233af05e679efb96b1851550ea95bbb64b7c490b0f5aa52996c11e92a20",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pexpect_4.8.0_py2.py3_none_any",
        package_name = "pexpect",
        package_version = "4.8.0",
        filename = "pexpect-4.8.0-py2.py3-none-any.whl",
        sha256 = "0b48a55dcb3c05f3329815901ea4fc1537514d6ba867a152b581d69ae3710937",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pickleshare_0.7.5_py2.py3_none_any",
        package_name = "pickleshare",
        package_version = "0.7.5",
        filename = "pickleshare-0.7.5-py2.py3-none-any.whl",
        sha256 = "9649af414d74d4df115d5d718f82acb59c9d418196b7b4290ed47a12ce62df56",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_platformdirs_3.11.0_py3_none_any",
        package_name = "platformdirs",
        package_version = "3.11.0",
        filename = "platformdirs-3.11.0-py3-none-any.whl",
        sha256 = "e9d171d00af68be50e9202731309c4e658fd8bc76f55c11c7dd760d023bda68e",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pre_commit_3.3.3_py2.py3_none_any",
        package_name = "pre-commit",
        package_version = "3.3.3",
        filename = "pre_commit-3.3.3-py2.py3-none-any.whl",
        sha256 = "10badb65d6a38caff29703362271d7dca483d01da88f9d7e05d0b97171c136cb",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_prometheus_client_0.18.0_py3_none_any",
        package_name = "prometheus-client",
        package_version = "0.18.0",
        filename = "prometheus_client-0.18.0-py3-none-any.whl",
        sha256 = "8de3ae2755f890826f4b6479e5571d4f74ac17a81345fe69a6778fdb92579184",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_prompt_toolkit_3.0.39_py3_none_any",
        package_name = "prompt-toolkit",
        package_version = "3.0.39",
        filename = "prompt_toolkit-3.0.39-py3-none-any.whl",
        sha256 = "9dffbe1d8acf91e3de75f3b544e4842382fc06c6babe903ac9acb74dc6e08d88",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_psutil_5.9.6_cp36_abi3_macosx_10_9_x86_64",
        package_name = "psutil",
        package_version = "5.9.6",
        filename = "psutil-5.9.6-cp36-abi3-macosx_10_9_x86_64.whl",
        sha256 = "c69596f9fc2f8acd574a12d5f8b7b1ba3765a641ea5d60fb4736bf3c08a8214a",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_psutil_5.9.6_cp36_abi3_manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "psutil",
        package_version = "5.9.6",
        filename = "psutil-5.9.6-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "748c9dd2583ed86347ed65d0035f45fa8c851e8d90354c122ab72319b5f366f4",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_psutil_5.9.6_cp38_abi3_macosx_11_0_arm64",
        package_name = "psutil",
        package_version = "5.9.6",
        filename = "psutil-5.9.6-cp38-abi3-macosx_11_0_arm64.whl",
        sha256 = "daecbcbd29b289aac14ece28eca6a3e60aa361754cf6da3dfb20d4d32b6c7f57",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_ptyprocess_0.7.0_py2.py3_none_any",
        package_name = "ptyprocess",
        package_version = "0.7.0",
        filename = "ptyprocess-0.7.0-py2.py3-none-any.whl",
        sha256 = "4b41f3967fce3af57cc7e94b888626c18bf37a083e3651ca8feeb66d492fef35",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pure_eval_0.2.2_py3_none_any",
        package_name = "pure-eval",
        package_version = "0.2.2",
        filename = "pure_eval-0.2.2-py3-none-any.whl",
        sha256 = "01eaab343580944bc56080ebe0a674b39ec44a945e6d09ba7db3cb8cec289350",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pycparser_2.21_py2.py3_none_any",
        package_name = "pycparser",
        package_version = "2.21",
        filename = "pycparser-2.21-py2.py3-none-any.whl",
        sha256 = "8ee45429555515e1f6b185e78100aea234072576aa43ab53aefcae078162fca9",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pygments_2.16.1_py3_none_any",
        package_name = "pygments",
        package_version = "2.16.1",
        filename = "Pygments-2.16.1-py3-none-any.whl",
        sha256 = "13fc09fa63bc8d8671a6d247e1eb303c4b343eaee81d861f3404db2935653692",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_python_dateutil_2.8.2_py2.py3_none_any",
        package_name = "python-dateutil",
        package_version = "2.8.2",
        filename = "python_dateutil-2.8.2-py2.py3-none-any.whl",
        sha256 = "961d03dc3453ebbc59dbdea9e4e11c5651520a876d0f4db161e8674aae935da9",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_python_json_logger_2.0.7_py3_none_any",
        package_name = "python-json-logger",
        package_version = "2.0.7",
        filename = "python_json_logger-2.0.7-py3-none-any.whl",
        sha256 = "f380b826a991ebbe3de4d897aeec42760035ac760345e57b812938dc8b35e2bd",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pyyaml_6.0.1_cp39_cp39_macosx_10_9_x86_64",
        package_name = "pyyaml",
        package_version = "6.0.1",
        filename = "PyYAML-6.0.1-cp39-cp39-macosx_10_9_x86_64.whl",
        sha256 = "9eb6caa9a297fc2c2fb8862bc5370d0303ddba53ba97e71f08023b6cd73d16a8",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pyyaml_6.0.1_cp39_cp39_macosx_11_0_arm64",
        package_name = "pyyaml",
        package_version = "6.0.1",
        filename = "PyYAML-6.0.1-cp39-cp39-macosx_11_0_arm64.whl",
        sha256 = "c8098ddcc2a85b61647b2590f825f3db38891662cfc2fc776415143f599bb859",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pyyaml_6.0.1_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "pyyaml",
        package_version = "6.0.1",
        filename = "PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "bc1bf2925a1ecd43da378f4db9e4f799775d6367bdb94671027b73b393a7c42c",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pyzmq_25.1.1_cp39_cp39_macosx_10_15_universal2",
        package_name = "pyzmq",
        package_version = "25.1.1",
        filename = "pyzmq-25.1.1-cp39-cp39-macosx_10_15_universal2.whl",
        sha256 = "03b3f49b57264909aacd0741892f2aecf2f51fb053e7d8ac6767f6c700832f45",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_pyzmq_25.1.1_cp39_cp39_manylinux_2_12_x86_64.manylinux2010_x86_64",
        package_name = "pyzmq",
        package_version = "25.1.1",
        filename = "pyzmq-25.1.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl",
        sha256 = "d457aed310f2670f59cc5b57dcfced452aeeed77f9da2b9763616bd57e4dbaae",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_referencing_0.30.2_py3_none_any",
        package_name = "referencing",
        package_version = "0.30.2",
        filename = "referencing-0.30.2-py3-none-any.whl",
        sha256 = "449b6669b6121a9e96a7f9e410b245d471e8d48964c67113ce9afe50c8dd7bdf",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_requests_2.31.0_py3_none_any",
        package_name = "requests",
        package_version = "2.31.0",
        filename = "requests-2.31.0-py3-none-any.whl",
        sha256 = "58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_rfc3339_validator_0.1.4_py2.py3_none_any",
        package_name = "rfc3339-validator",
        package_version = "0.1.4",
        filename = "rfc3339_validator-0.1.4-py2.py3-none-any.whl",
        sha256 = "24f6ec1eda14ef823da9e36ec7113124b39c04d50a4d3d3a3c2859577e7791fa",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_rfc3986_validator_0.1.1_py2.py3_none_any",
        package_name = "rfc3986-validator",
        package_version = "0.1.1",
        filename = "rfc3986_validator-0.1.1-py2.py3-none-any.whl",
        sha256 = "2f235c432ef459970b4306369336b9d5dbdda31b510ca1e327636e01f528bfa9",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_rpds_py_0.12.0_cp39_cp39_macosx_10_7_x86_64",
        package_name = "rpds-py",
        package_version = "0.12.0",
        filename = "rpds_py-0.12.0-cp39-cp39-macosx_10_7_x86_64.whl",
        sha256 = "1096ca0bf2d3426cbe79d4ccc91dc5aaa73629b08ea2d8467375fad8447ce11a",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_rpds_py_0.12.0_cp39_cp39_macosx_11_0_arm64",
        package_name = "rpds-py",
        package_version = "0.12.0",
        filename = "rpds_py-0.12.0-cp39-cp39-macosx_11_0_arm64.whl",
        sha256 = "48aa98987d54a46e13e6954880056c204700c65616af4395d1f0639eba11764b",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_rpds_py_0.12.0_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "rpds-py",
        package_version = "0.12.0",
        filename = "rpds_py-0.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "6f5dcb658d597410bb7c967c1d24eaf9377b0d621358cbe9d2ff804e5dd12e81",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_send2trash_1.8.2_py3_none_any",
        package_name = "send2trash",
        package_version = "1.8.2",
        filename = "Send2Trash-1.8.2-py3-none-any.whl",
        sha256 = "a384719d99c07ce1eefd6905d2decb6f8b7ed054025bb0e618919f945de4f679",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_setuptools_68.2.2_py3_none_any",
        package_name = "setuptools",
        package_version = "68.2.2",
        filename = "setuptools-68.2.2-py3-none-any.whl",
        sha256 = "b454a35605876da60632df1a60f736524eb73cc47bbc9f3f1ef1b644de74fd2a",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_six_1.16.0_py2.py3_none_any",
        package_name = "six",
        package_version = "1.16.0",
        filename = "six-1.16.0-py2.py3-none-any.whl",
        sha256 = "8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_sniffio_1.3.0_py3_none_any",
        package_name = "sniffio",
        package_version = "1.3.0",
        filename = "sniffio-1.3.0-py3-none-any.whl",
        sha256 = "eecefdce1e5bbfb7ad2eeaabf7c1eeb404d7757c379bd1f7e5cce9d8bf425384",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_soupsieve_2.5_py3_none_any",
        package_name = "soupsieve",
        package_version = "2.5",
        filename = "soupsieve-2.5-py3-none-any.whl",
        sha256 = "eaa337ff55a1579b6549dc679565eac1e3d000563bcb1c8ab0d0fefbc0c2cdc7",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_stack_data_0.6.3_py3_none_any",
        package_name = "stack-data",
        package_version = "0.6.3",
        filename = "stack_data-0.6.3-py3-none-any.whl",
        sha256 = "d5558e0c25a4cb0853cddad3d77da9891a08cb85dd9f9f91b9f8cd66e511e695",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_terminado_0.17.1_py3_none_any",
        package_name = "terminado",
        package_version = "0.17.1",
        filename = "terminado-0.17.1-py3-none-any.whl",
        sha256 = "8650d44334eba354dd591129ca3124a6ba42c3d5b70df5051b6921d506fdaeae",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_tinycss2_1.2.1_py3_none_any",
        package_name = "tinycss2",
        package_version = "1.2.1",
        filename = "tinycss2-1.2.1-py3-none-any.whl",
        sha256 = "2b80a96d41e7c3914b8cda8bc7f705a4d9c49275616e886103dd839dfc847847",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_tokenize_rt_5.2.0_py2.py3_none_any",
        package_name = "tokenize-rt",
        package_version = "5.2.0",
        filename = "tokenize_rt-5.2.0-py2.py3-none-any.whl",
        sha256 = "b79d41a65cfec71285433511b50271b05da3584a1da144a0752e9c621a285289",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_tomli_2.0.1_py3_none_any",
        package_name = "tomli",
        package_version = "2.0.1",
        filename = "tomli-2.0.1-py3-none-any.whl",
        sha256 = "939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_tornado_6.3.3_cp38_abi3_macosx_10_9_universal2",
        package_name = "tornado",
        package_version = "6.3.3",
        filename = "tornado-6.3.3-cp38-abi3-macosx_10_9_universal2.whl",
        sha256 = "502fba735c84450974fec147340016ad928d29f1e91f49be168c0a4c18181e1d",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_tornado_6.3.3_cp38_abi3_macosx_10_9_x86_64",
        package_name = "tornado",
        package_version = "6.3.3",
        filename = "tornado-6.3.3-cp38-abi3-macosx_10_9_x86_64.whl",
        sha256 = "805d507b1f588320c26f7f097108eb4023bbaa984d63176d1652e184ba24270a",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_tornado_6.3.3_cp38_abi3_manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64",
        package_name = "tornado",
        package_version = "6.3.3",
        filename = "tornado-6.3.3-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        sha256 = "71a8db65160a3c55d61839b7302a9a400074c9c753040455494e2af74e2501f2",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_traitlets_5.13.0_py3_none_any",
        package_name = "traitlets",
        package_version = "5.13.0",
        filename = "traitlets-5.13.0-py3-none-any.whl",
        sha256 = "baf991e61542da48fe8aef8b779a9ea0aa38d8a54166ee250d5af5ecf4486619",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_types_python_dateutil_2.8.19.14_py3_none_any",
        package_name = "types-python-dateutil",
        package_version = "2.8.19.14",
        filename = "types_python_dateutil-2.8.19.14-py3-none-any.whl",
        sha256 = "f977b8de27787639986b4e28963263fd0e5158942b3ecef91b9335c130cb1ce9",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_typing_extensions_4.8.0_py3_none_any",
        package_name = "typing-extensions",
        package_version = "4.8.0",
        filename = "typing_extensions-4.8.0-py3-none-any.whl",
        sha256 = "8f92fc8806f9a6b641eaa5318da32b44d401efaac0f6678c9bc448ba3605faa0",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_uri_template_1.3.0_py3_none_any",
        package_name = "uri-template",
        package_version = "1.3.0",
        filename = "uri_template-1.3.0-py3-none-any.whl",
        sha256 = "a44a133ea12d44a0c0f06d7d42a52d71282e77e2f937d8abd5655b8d56fc1363",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_urllib3_2.0.7_py3_none_any",
        package_name = "urllib3",
        package_version = "2.0.7",
        filename = "urllib3-2.0.7-py3-none-any.whl",
        sha256 = "fdb6d215c776278489906c2f8916e6e7d4f5a9b602ccbcfdf7f016fc8da0596e",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_virtualenv_20.24.6_py3_none_any",
        package_name = "virtualenv",
        package_version = "20.24.6",
        filename = "virtualenv-20.24.6-py3-none-any.whl",
        sha256 = "520d056652454c5098a00c0f073611ccbea4c79089331f60bf9d7ba247bb7381",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_wcwidth_0.2.9_py2.py3_none_any",
        package_name = "wcwidth",
        package_version = "0.2.9",
        filename = "wcwidth-0.2.9-py2.py3-none-any.whl",
        sha256 = "9a929bd8380f6cd9571a968a9c8f4353ca58d7cd812a4822bba831f8d685b223",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_webcolors_1.13_py3_none_any",
        package_name = "webcolors",
        package_version = "1.13",
        filename = "webcolors-1.13-py3-none-any.whl",
        sha256 = "29bc7e8752c0a1bd4a1f03c14d6e6a72e93d82193738fa860cbff59d0fcc11bf",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_webencodings_0.5.1_py2.py3_none_any",
        package_name = "webencodings",
        package_version = "0.5.1",
        filename = "webencodings-0.5.1-py2.py3-none-any.whl",
        sha256 = "a0af1213f3c2226497a97e2b3aa01a7e4bee4f403f95be16fc9acd2947514a78",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_websocket_client_1.6.4_py3_none_any",
        package_name = "websocket-client",
        package_version = "1.6.4",
        filename = "websocket_client-1.6.4-py3-none-any.whl",
        sha256 = "084072e0a7f5f347ef2ac3d8698a5e0b4ffbfcab607628cadabc650fc9a83a24",
        index = "https://pypi.org",
    )

    maybe(
        pypi_file,
        name = "poetry_lock_wheel_zipp_3.17.0_py3_none_any",
        package_name = "zipp",
        package_version = "3.17.0",
        filename = "zipp-3.17.0-py3-none-any.whl",
        sha256 = "0e923e726174922dce09c53c59ad483ff7bbb8e572e00c7f7c46b88556409f31",
        index = "https://pypi.org",
    )

