load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "mdformat",
    srcs = ["mdformat.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@pip//:mdformat",
    ],
)
