load("//platform/constraint:constraint.bzl", "darwin_arm64", "darwin_x86_64", "linux_x86_64")

platform(
    name = "linux_x86_64",
    constraint_values = linux_x86_64,
)

platform(
    name = "darwin_x86_64",
    constraint_values = darwin_x86_64,
)

platform(
    name = "darwin_arm64",
    constraint_values = darwin_arm64,
)
