repos:
  - repo: local
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: bazel run --config=quiet black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi, jupyter]
      - id: cpplint
        name: cpplint
        entry: bazel run --config=quiet cpplint
        description: "Static code analysis of C/C++ files"
        language: python
        files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
      - id: buildfier
        name: buildfier
        entry: bazel run --config=quiet buildifier
        description: "Lint Bazel Files"
        language: python
        files: (BUILD|.bazel|.bzl)$
      - id: rustfmt
        name: rustfmt
        entry: bazel run --config=quiet rustfmt
        description: "Lint Rist Files"
        language: rust
        files: (.rs)$
      - id: mdformat
        name: mdformat
        entry: bazel run --config=quiet mdformat
        description: "Lint Bazel Files"
        language: python
        files: \.(md)$