repos:
  - repo: local
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: bazel run black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi, jupyter]
      - id: cpplint
        name: cpplint
        entry: bazel run cpplint
        description: "Static code analysis of C/C++ files"
        language: python
        files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
      - id: buildfier
        name: buildfier
        entry: bazel run buildifier
        description: "Lint Bazel Files"
        language: python
        files: (BUILD|MODULE|)(.bazel|.bzl)$
