load("//platform:platform.bzl", "constraints")

config_setting(
    name = "linux_x86_64",
    constraint_values = constraints.linux_x86_64,
)

config_setting(
    name = "darwin_x86_64",
    constraint_values = constraints.darwin_x86_64,
)

config_setting(
    name = "darwin_arm64",
    constraint_values = constraints.darwin_arm64,
)

config_setting(
    name = "windows_x86_64",
    constraint_values = constraints.windows_x86_64,
)
