name: macOS

on: [push]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: pre-commit
        run: bazelisk run pre-commit
      - name: build
        run: bazelisk build //...
      - name: test
        run: bazelisk test //...
