name: Windows

on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: pre-commit
        run: bazelisk run pre-commit -- run --all-files
      - name: build
        run: bazelisk build //...
      - name: test
        run: bazelisk test //...